#!/usr/bin/env python3
# Cowork Local Viewer — build.py
# authors: 7hud41
# license: MIT
#
# Generates a single self-contained index.html (fonts, JSZip, engine and loader inlined) that works offline.
#
#   python3 build.py                 -> index.html (local sessions + projects + index + archives)
#   python3 build.py --mode archive  -> index.html (archive reader only)
#   python3 build.py -o out.html     -> custom output path
import argparse, base64, json, os

ROOT = os.path.dirname(os.path.abspath(__file__))
ENGINE = os.path.join(ROOT, "engine")
SRC = os.path.join(ROOT, "src")

ap = argparse.ArgumentParser()
ap.add_argument("--mode", choices=["local", "archive"], default="local")
ap.add_argument("-o", "--out", default=os.path.join(ROOT, "index.html"))
args = ap.parse_args()
MODE = args.mode

def read(p): return open(p, encoding="utf-8").read()
def b64(p): return base64.b64encode(open(p, "rb").read()).decode()

FONTS = ["LibertinusSerif-Regular", "LibertinusSerif-Bold", "LibertinusSerif-Italic", "LibertinusSerif-BoldItalic", "FiraCode-Regular", "FiraCode-Bold"]

viewer_css = read(os.path.join(ENGINE, "viewer.css"))
viewer_js = read(os.path.join(ENGINE, "viewer.js"))
i18n_js = read(os.path.join(ENGINE, "i18n.js"))
jszip = read(os.path.join(ENGINE, "jszip.min.js"))
engine = read(os.path.join(ENGINE, "archive.js"))
loader = read(os.path.join(SRC, "loader.js"))

# 1) CSS with embedded fonts
css_inline = viewer_css
for f in FONTS:
    css_inline = css_inline.replace(f'url("fonts/{f}.woff2")', f'url("data:font/woff2;base64,{b64(os.path.join(ENGINE, "fonts", f + ".woff2"))}")')

# 2) resources served through a fake chrome.runtime.getURL (data: URLs) for buildTranscriptHtml
def data_url(mime, s): return f"data:{mime};base64," + base64.b64encode(s.encode("utf-8")).decode()
RES = {"viewer.css": data_url("text/css", viewer_css), "viewer.js": data_url("text/javascript", viewer_js)}
for f in FONTS:
    RES["fonts/" + f + ".woff2"] = "data:font/woff2;base64," + b64(os.path.join(ENGINE, "fonts", f + ".woff2"))
res_js = "const RES = " + json.dumps(RES) + ";\nwindow.chrome = { runtime: { getURL: p => RES[p] || p } };\nwindow.VIEWER_MODE = " + json.dumps(MODE) + ";\nwindow.ARCHIVE_HOST = true;"

# Inlining safety: a literal "</script>" inside inline JS would close the HTML tag.
# Inside a JS string/template, "<\/script>" equals "</script>", so the escape does not change the code.
def safe_inline(js): return js.replace("</script>", "<\\/script>")
jszip, viewer_js, i18n_js, engine, loader = map(safe_inline, (jszip, viewer_js, i18n_js, engine, loader))

if MODE == "archive":
    TITLE = "Cowork Archive Viewer"
    DROP_BIG = "Drop a downloaded archive here: a <b>ZIP</b> or its unzipped folder (the one containing <b>events.json</b>)"
    DROP_HOW = '<span data-i18n-html="Same view as when it was exported: reading or full-details mode, day filter, day export, re-export. Drops add up.">Same view as when it was exported: reading or full-details mode, day filter, day export, re-export. Drops add up.</span><br>'
    EXTRA_CONTROLS = ""
else:
    TITLE = "Cowork Local Viewer"
    DROP_BIG = "Drop a <b>local_…</b> folder and its <b>local_….json</b> here (select both in the Finder, drop them together)"
    DROP_HOW = (
        '<span data-i18n-html="You can drop several sessions at once. Dropping works anywhere on the page, and drops add up.">You can drop several sessions at once. Dropping works anywhere on the page, and drops add up.</span><br>'
        '<span data-i18n-html="<b>Projects:</b> drop <b>spaces.json</b> (in <code>Application Support/Claude/</code>) to see which project each session belongs to."><b>Projects:</b> drop <b>spaces.json</b> (in <code>Application Support/Claude/</code>) to see which project each session belongs to.</span><br>'
        '<span data-i18n-html="<b>Reopen an archive:</b> drop a downloaded <b>ZIP</b> here (or its unzipped folder): same view, reading/full mode, day filter, re-export."><b>Reopen an archive:</b> drop a downloaded <b>ZIP</b> here (or its unzipped folder): same view, reading/full mode, day filter, re-export.</span><br>'
        '<span data-i18n-html="<b>Index of all sessions:</b> drop only the <b>local_….json</b> files (in the Finder, type “.json” in the search box of the sessions folder, select all, drop) then “Build the index”."><b>Index of all sessions:</b> drop only the <b>local_….json</b> files (in the Finder, type “.json” in the search box of the sessions folder, select all, drop) then “Build the index”.</span><br>'
    )
    EXTRA_CONTROLS = (
        '<select id="projectSelect" class="ctl" hidden style="max-width:260px;"></select>'
        '<button id="csvBtn" class="btn" style="text-transform:none;letter-spacing:0;" data-i18n="Build the index (.csv + .md)" data-i18n-title="Downloads a .csv (Numbers/Excel) and a .md: project, title, id, dates, size — for every listed session">Build the index (.csv + .md)</button>'
    )

html = f"""<!DOCTYPE html>
<!-- {TITLE} — generated by build.py · authors: 7hud41 · license: MIT -->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title data-i18n="{TITLE}">{TITLE}</title>
<style>
{css_inline}
header {{ position: sticky; top: 0; z-index: 5; background: rgba(243,239,231,.96); backdrop-filter: blur(6px); border-bottom: 1px solid var(--line); padding: 12px 24px; }}
h1 {{ font-size: 18px; margin: 0 0 2px; }}
.sub {{ color: var(--muted); font-size: 13px; }}
.toolbar {{ display: flex; flex-wrap: wrap; gap: 10px; align-items: center; margin-top: 10px; }}
button:not(.btn) {{ padding: 8px 14px; font-size: 13px; font-weight: 600; border: 0; border-radius: 8px; background: var(--accent); color: #fff; cursor: pointer; }}
button:not(.btn):disabled {{ background: #cfcac2; color: #fff; cursor: default; }}
.opts {{ font-size: 12px; color: var(--muted); display: flex; flex-wrap: wrap; gap: 12px; }}
.bar {{ height: 6px; background: #e6e2da; border-radius: 3px; overflow: hidden; margin-top: 10px; }}
.bar > div {{ height: 100%; width: 0; background: var(--accent); transition: width .2s; }}
#log {{ font-family: "Fira Code", ui-monospace, Menlo, monospace; font-size: 11.5px; line-height: 1.5; white-space: pre-wrap; background: var(--paper); border: 1px solid var(--line); border-radius: 8px; padding: 10px 12px; max-height: 160px; overflow: auto; margin: 16px auto 0; }}
#log:empty {{ display: none; }}
.ok {{ color: #2f7a3e; }} .warn {{ color: #b26b00; }} .err {{ color: #b3261e; }}
.safe {{ background: #eef6ea; border: 1px solid #cfe6c2; color: #2f5a34; font-size: 12.5px; border-radius: 10px; padding: 8px 12px; margin: 14px auto 0; }}
.drop {{ margin: 14px auto 0; border: 2px dashed #cbb9aa; border-radius: 14px; background: var(--paper); padding: 26px; text-align: center; color: var(--muted); transition: .15s; }}
.drop.over {{ border-color: var(--accent); background: #fff7f2; color: var(--ink); }}
.drop b {{ color: var(--ink); }}
.dstatus {{ margin: 10px auto 0; font-size: 13px; padding: 8px 12px; border-radius: 8px; background: #fff; border: 1px solid var(--line); color: var(--ink); white-space: pre-wrap; }}
.dstatus.ok {{ border-color: #cfe6c2; background: #eef6ea; color: #2f5a34; }}
.dstatus.warn {{ border-color: #f0d9a8; background: #fff7e6; color: #7a5200; }}
.dstatus.err {{ border-color: #f0b8b3; background: #fff0ee; color: #8a1f17; }}
.drop .big {{ font-size: 17px; color: var(--ink); line-height: 1.5; }}
.drop label.btn {{ display: inline-block; margin-top: 8px; cursor: pointer; }}
.drop .how {{ font-size: 13px; color: var(--muted); margin-top: 12px; line-height: 1.5; }}
input[type=file] {{ display: none; }}
#sessionsCard {{ margin: 14px auto 0; background: var(--paper); border: 1px solid var(--line); border-radius: 12px; padding: 10px 12px; }}
#sessionsCard h2 {{ font-size: 12px; margin: 0 0 8px; color: var(--muted); text-transform: uppercase; letter-spacing: .04em; display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }}
#sessionsCard h2 .ctl, #sessionsCard h2 input {{ text-transform: none; letter-spacing: 0; font-weight: 400; }}
#sessions {{ max-height: 260px; overflow: auto; }}
.srow {{ padding: 8px 10px; border-radius: 8px; cursor: pointer; }}
.srow:hover {{ background: #f4f1ea; }}
.srow.sel {{ background: #fdece4; }}
.stitle {{ font-size: 14px; font-weight: 600; }}
.smeta {{ font-size: 11.5px; color: var(--muted); }}
.srow.noconv .stitle {{ color: #6b665e; font-weight: 500; }}
.pchip {{ display: inline-block; font-size: 11px; font-weight: 600; letter-spacing: .02em; padding: 1px 8px; border-radius: 999px; background: #e7f0e2; color: #2f5a34; border: 1px solid #cfe6c2; margin-right: 8px; vertical-align: 1px; }}
.pchip.soft {{ background: #fff3e0; color: #7a5200; border-color: #f0d9a8; }}
.ctl {{ padding: 6px 8px; font-size: 12.5px; border: 1px solid var(--line); border-radius: 8px; background: #fff; }}
#sessionSearch {{ flex: 1; min-width: 160px; padding: 6px 10px; font-size: 13px; border: 1px solid var(--line); border-radius: 8px; }}
.lang {{ margin-left: auto; display: inline-flex; gap: 6px; align-items: center; font-size: 12px; color: var(--muted); }}
</style>
</head>
<body class="mode-hr">
<header>
  <div class="wrap">
    <h1 data-i18n="{TITLE}">{TITLE}</h1>
    <div class="sub"><span data-i18n="Session">Session</span> <code id="sid">—</code></div>
    <div class="toolbar">
      <button id="zipBtn" disabled data-i18n="Download ZIP">Download ZIP</button>
      <button id="zipDayBtn" disabled data-i18n="ZIP by day" data-i18n-title="One folder per day, each with the full .md of that day and its images">ZIP by day</button>
      <button id="modeBtn" class="btn" data-mode="hr">Mode: reading</button>
      <span id="dayExport" hidden style="display:inline-flex;gap:6px;align-items:center;">
        <select id="daySelect" class="ctl" style="max-width:300px;"></select>
        <button id="dayBtn" class="btn" disabled data-i18n="Export this day (.md)">Export this day (.md)</button>
      </span>
      <span id="tzWrap" style="display:inline-flex;gap:6px;align-items:center;" data-i18n-title="Files only keep the UTC instant, not the place: pick the time zone you were in during this session. Remembered per session.">
        <label for="tzSelect" style="font-size:12px;color:var(--muted);" data-i18n="Time zone:">Time zone:</label>
        <select id="tzSelect" class="ctl"></select>
        <button id="tzDefaultBtn" class="btn" data-i18n="Default" data-i18n-title="Use this time zone for every session without a remembered choice">Default</button>
      </span>
      <span class="lang"><label for="langSelect" data-i18n="Language">Language</label><select id="langSelect" class="ctl"></select></span>
      <div class="opts">
        <label><input type="checkbox" id="optImages" checked> <span data-i18n="uploaded images">uploaded images</span></label>
        <label><input type="checkbox" id="optWritten" checked> <span data-i18n="files written by Claude">files written by Claude</span></label>
        <label><input type="checkbox" id="optTranscript" checked> <span data-i18n="transcript.md + transcript.html">transcript.md + transcript.html</span></label>
        <label><input type="checkbox" id="optTech"> <span data-i18n="show technical events">show technical events</span></label>
      </div>
    </div>
    <div class="bar"><div id="progress"></div></div>
  </div>
</header>

<div class="wrap">
  <div class="safe">🔒 <b data-i18n="Read-only, 100% local.">Read-only, 100% local.</b> <span data-i18n="This page runs offline in your browser: nothing is sent anywhere, nothing on your disk is modified. It reads what you drop and lets you view and export it.">This page runs offline in your browser: nothing is sent anywhere, nothing on your disk is modified. It reads what you drop and lets you view and export it.</span></div>
  <div id="drop" class="drop">
    <div class="big" data-i18n-html="{DROP_BIG}">{DROP_BIG}</div>
    <div class="how">{DROP_HOW}
    <label class="btn" for="dirInput" data-i18n="…or choose a folder">…or choose a folder</label>
    <input type="file" id="dirInput" webkitdirectory directory multiple></div>
  </div>
  <div id="dropStatus" class="dstatus" hidden></div>
  <div id="sessionsCard" hidden>
    <h2><span data-i18n="Sessions found — click to display">Sessions found — click to display</span><span id="sessionsCount" style="font-weight:400;text-transform:none;letter-spacing:0;"></span>{EXTRA_CONTROLS}<input id="sessionSearch" type="search" placeholder="Search a title…" data-i18n-placeholder="Search a title…" hidden></h2>
    <div id="sessions"></div>
  </div>
  <div id="log"></div>
  <div id="summary"></div>
</div>
<div id="conv"></div>

<script>{res_js}</script>
<script>{jszip}</script>
<script>{i18n_js}</script>
<script>{viewer_js}</script>
<script>{engine}</script>
<script>{loader}</script>
</body>
</html>
"""
os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
open(args.out, "w", encoding="utf-8").write(html)
print("OK ->", args.out, f"({len(html) / 1024 / 1024:.1f} MB, mode={MODE})")
